name: police
version: git
summary: Police is a rule-based string interpolation utility.
description: |
  Police is a CLI front-end to Interpol, a flexible string interpolation
  library. It can be used to generate lists of entries based on a set of
  rules, for example for use in penetration testing or fuzzing.

grade: devel
confinement: strict

parts:
  police:
    source: .
    plugin: go
    go-importpath: bitbucket.org/vahidi/interpol

apps:
  police:
    command: police
