name: police
#version-script: cmd/police/police -version
version: git
summary: Police is a rule-based string interpolation utility.
description: |
  Police is a CLI front-end to Interpol, a flexible string interpolation
  library. It can be used to generate lists of entries based on a set of
  rules, for example for use in penetration testing or fuzzing.

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    run-on: [armhf, arm64, amd64, i386]

parts:
  police:
    source: .
    plugin: go


apps:
  police:
    command: bin/police
#    plugs:
#      - read-files
